const COLORS: Record<string, string | null> = {
    "Agir, la droite constructive" : "c-43519E",
    "Alliance royale" : "c-ADD8E6",
    "Centre des démocrates sociaux" : "c-00A1DE",
    "Centre national des indépendants et paysans" : "c-26C4EC",
    "Debout la France" : "c-0087CD",
    "Démocrates" : "c-FF9900",
    "Droit de chasse" : "c-2E8B57",
    "Droite Républicaine" : "c-0066CC",
    "Écologiste - Solidarité et Territoires" : "c-00C000",
    "Eusko Alkartasuna" : "c-77AC1C",
    "Force européenne démocrate" : "c-00CCCC",
    "Front national": "c-0D378A",
    "Gauche républicaine et socialiste": "c-D53150",
    "Génération.s": "c-CC1E54",
    "Groupe Communiste Républicain Citoyen et Écologiste - Kanaky": "c-888888",
    "Groupe Les Indépendants - République et Territoires": "c-888888",
    "Groupe Rassemblement des démocrates, progressistes et indépendants": "c-888888",
    "Herritarren Zerrenda": "c-FB4B08",
    "Horizons": "c-0001AA",
    "Identité-Libertés": "c-1C2951",
    "Jeanne": "c-1C2951",
    "L'Après": "c-7B68EE",
    "La France humaniste": "c-062D66",
    "La France insoumise": "c-CC2443",
    "La Gauche moderne": "c-EE82EE",
    "Le Mouvement de la ruralité": "c-0049A1",
    "Les Centristes":  "c-6F97CF",
    "Les Écologistes – Europe Écologie Les Verts":  "c-4BB166",
    "Les Républicains":  "c-0066CC",
    "Libertés, Indépendants, Outre-mer et Territoires":  "c-AADDFF",
    "Lutte ouvrière":  "c-E32831",
    "Mouvement démocrate":  "c-EF5327",
    "Mouvement des progressistes":  "c-9C005E",
    "Mouvement national républicain":  "c-404040",
    "Mouvement pour la France":  "c-00008B",
    "Mouvement radical":  "c-D8008A",
    "Non-inscrits":  "c-AAAAAA",
    "Nouveau Front Populaire":  "c-E8555E",
    "Nouveau Parti anticapitaliste":  "c-C0081F",
    "Nouvelle Action royaliste": "c-000000",
    "Nouvelle Donne": "c-D11677",
    "Parti chrétien-démocrate": "c-298DB5",
    "Parti communiste breton": "c-DD0000",
    "Parti communiste des ouvriers de France": "c-DC041B",
    "Parti communiste français": "c-E4002A",
    "Parti communiste internationaliste": "c-DD0000",
    "Parti communiste réunionnais": "c-DD0000",
    "Parti communiste révolutionnaire de France": "c-F71A01",
    "Parti de gauche": "c-AA0000",
    "Parti de la France": "c-32688F",
    "Parti des forces nouvelles": "c-1C2951",
    "Parti des travailleurs": "c-B22222",
    "Parti libéral démocrate": "c-0080FF",
    "Parti radical": "c-E0B0FF",
    "Parti radical de gauche": "c-F0C200",
    "Parti républicain": "c-0072BB",
    "Parti socialiste": "c-FF8080",
    "Place publique": "c-FFF100",
    "Rassemblement Démocratique et Social Européen": "c-F0A000",
    "Rassemblement National": "c-0D378A",
    "Rassemblement pour la République": "c-0066CC",
    "Reconquête": "c-0B0B66",
    "Renaissance": "c-FFD600",
    "Révolution écologique pour le vivant": "c-228B22",
    "Solidarité et progrès": "c-000000",
    "Solution démocratique": "c-07545E",
    "Territoires de progrès": "c-E94662",
    "Union Centriste": "c-FF9900",
    "Union des démocrates et indépendants": "c-35A2EF",
    "Union des démocrates pour la République": "c-8040C0",
    "Union des droites pour la République": "c-888888",
    "Union populaire républicaine": "c-057C85",
    "Union pour la démocratie française": "c-FF9E23",
    "Union pour un mouvement populaire": "c-0066CC",
}

export { COLORS };